import { createSlice } from '@reduxjs/toolkit';

// Create a slice for coupons
const couponSlice = createSlice({
    name: 'coupons',
    initialState: {
        coupons: [],
    },
    reducers: {
        // Action to set coupons
        setCoupons: (state, action) => {
            state.coupons = action.payload;
        },
        // Action to add a coupon
        addCoupon: (state, action) => {
            state.coupons.push(action.payload);
        },
        // Action to remove a coupon
        removeCoupon: (state, action) => {
            state.coupons = state.coupons.filter(coupon => coupon.id !== action.payload);
        },
        // Action to update a coupon
        updateCoupon: (state, action) => {
            const index = state.coupons.findIndex(coupon => coupon.id === action.payload.id);
            if (index !== -1) {
                state.coupons[index] = action.payload;
            }
        },
    },
});

// Export the actions generated by the slice
export const { setCoupons, addCoupon, removeCoupon, updateCoupon } = couponSlice.actions;

// Export the reducer to be used in the store
export default couponSlice.reducer;
